#!name=My AdBlock Rules
#!desc=屏蔽 qt.nanrensvip01.cc 广告 JS

[rewrite_local]
^https?:\/\/qt\.nanrensvip01\.cc\/d\/s_gg\.js(\?.*)?$ url reject
^https?:\/\/qt\.nanrensvip01\.cc\/d\/x_gg\.js(\?.*)?$ url reject

[mitm]
hostname = qt.nanrensvip01.cc
